
# Other projects which deals with images in PHP and uses travis:
# https://github.com/JBZoo/Image
# https://travis-ci.org/peter279k/php-image-converter/builds

language: php

#php:
#  - 5.6
#  - 7.1
#  - 7.2
#  - 7.3

# cache composer?
#   https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
#   https://github.com/thephpleague/glide/blob/master/.travis.yml
cache:
  #apt: true
  directories:
    - "$HOME/opt"     # cache our imagick/gmagick install
    - $HOME/vips

addons:
  apt:
    packages:
      - libjpeg-dev
      - libpng-dev
      - libwebp-dev

      # following for vips (taken from https://github.com/libvips/php-vips/blob/master/.travis.yml)
      - gobject-introspection
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev

sudo: false

matrix:
  fast_finish: true
  include:
    #- php: 5.6
    #  env: UPLOADCOVERAGE=1
    #- php: 7.3
    - name: "Testing imagick install script"
      php: 7.1
      #dist: trusty
      dist: xenial
      #dist: bionic
      env:
      - UPLOADCOVERAGE=1
      - PHPSTAN=1
      - TESTSRCBUILD=1
      - VIPS_VERSION="8.6.3"
      #env: VIPS_VERSION="8.7.4"
  #allow_failures:

before_install:
  # VIPS
  - export PATH=$HOME/vips/bin:$PATH
  - export LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
  - export PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH
  - export PYTHONPATH=$HOME/vips/lib/python2.7/site-packages:$PYTHONPATH
  - export GI_TYPELIB_PATH=$HOME/vips/lib/girepository-1.0:$GI_TYPELIB_PATH
  - bash install-vips.sh
    --disable-debug
    --disable-dependency-tracking
    --disable-introspection
    --disable-static
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
    --without-orc
    --without-python
  - yes '' | pecl install vips

  # Update PATH so that travis can find our imagemagick / gmagick
  - export PATH=$HOME/opt/bin:$PATH

  # install imagick with webp support (if not already there) and update library paths
  - bash install-imagick-with-webp.sh
  - export LD_FLAGS=-L$HOME/opt/lib
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/opt/lib
  - export CPATH=$CPATH:$HOME/opt/include

  # install imagick extension (if not already there)
  - echo '' | pecl install imagick

  # GMagick

  - bash install-gmagick-with-webp.sh
  - export GMAGICK_PATH=$HOME/opt/bin

  # Hm, extension is not working yet. When I get to install the extension I get the message:
  #    "Please provide a path to GraphicsMagick-config program."
  #    According to here: https://stackoverflow.com/questions/8626558/please-provide-the-prefix-of-graphicsmagick-installation-autodetect
  #    it is because the libgraphicsmagick1-dev package is not installed
  #    But is that needed when we are building ?
  #- echo '' | pecl install gmagick-beta

before_script:
  #- echo $PATH
  - (composer self-update; true)
  - composer install
  - if [[ $PHPSTAN == 1 ]]; then composer require --dev phpstan/phpstan:"^0.11.5"; fi

script:
  - if [[ $TESTSRCBUILD == 1 ]]; then composer test-src-build; fi
  - composer test-src
  - if [[ $PHPSTAN == 1 ]]; then vendor/bin/phpstan analyse src --level=4; fi

after_script:
  - |
    if [[ $UPLOADCOVERAGE == 1 ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
