language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

dist: xenial

addons:
  apt:
    packages:
      - libjpeg-dev
      
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: UPLOADCOVERAGE=1
    - php: 7.3
      env: PHPSTAN=1

before_script:
  - (composer self-update; true)
  - composer install
  - if [[ $PHPSTAN == 1 ]]; then composer require --dev phpstan/phpstan:"^0.11.5"; fi

script:
  - composer test
  - if [[ $PHPSTAN == 1 ]]; then vendor/bin/phpstan analyse src --level=4; fi

after_script:
  - |
    if [[ $UPLOADCOVERAGE == 1 ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
